// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKCx9tVktsIJt6HeeXA8Xq7UmA0Fc7eyM',
    appId: '1:907410167636:web:f9a6d4cd21581ad9885ac1',
    messagingSenderId: '907410167636',
    projectId: 'bibliotecaapp-7b84f',
    authDomain: 'bibliotecaapp-7b84f.firebaseapp.com',
    storageBucket: 'bibliotecaapp-7b84f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp2CwaFiNYX8YU6rZY0dgvL-8tyTj0870',
    appId: '1:907410167636:android:a2b1f62f97d50513885ac1',
    messagingSenderId: '907410167636',
    projectId: 'bibliotecaapp-7b84f',
    storageBucket: 'bibliotecaapp-7b84f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUtZ6rPUUKdQSH3SeSb2Y4jb1LfHl9Ki8',
    appId: '1:907410167636:ios:45273f27d66bc9cb885ac1',
    messagingSenderId: '907410167636',
    projectId: 'bibliotecaapp-7b84f',
    storageBucket: 'bibliotecaapp-7b84f.firebasestorage.app',
    iosBundleId: 'com.example.bibliotecaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUtZ6rPUUKdQSH3SeSb2Y4jb1LfHl9Ki8',
    appId: '1:907410167636:ios:45273f27d66bc9cb885ac1',
    messagingSenderId: '907410167636',
    projectId: 'bibliotecaapp-7b84f',
    storageBucket: 'bibliotecaapp-7b84f.firebasestorage.app',
    iosBundleId: 'com.example.bibliotecaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKCx9tVktsIJt6HeeXA8Xq7UmA0Fc7eyM',
    appId: '1:907410167636:web:766c71c03b7269e4885ac1',
    messagingSenderId: '907410167636',
    projectId: 'bibliotecaapp-7b84f',
    authDomain: 'bibliotecaapp-7b84f.firebaseapp.com',
    storageBucket: 'bibliotecaapp-7b84f.firebasestorage.app',
  );
}
